spring:
  profiles:
    active: pro
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.55.164.62:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: Fls,./19910211
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 30
    minIdle: 30
    maxActive: 500
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

  cache:
    type: redis
    redis:
      time-to-live: 20s #缓存超时时间ms
      cache-null-values: false #是否缓存空值
  redis:
    port: 6379
    host: 106.55.164.62
    lettuce:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 0
    timeout: 10s  #redis 连接超时时间ms
    database: 0

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true

server:
  port: 9095
  servlet:
    context-path: /example

mybatis:
  typeAliasesPackage: com.neeson.example.model
  mapperLocations: classpath:mapper/*.xml

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL35Gc5yhS4vO54hY3N1cJWOgZfQhfRQCZKVHmwk2pVdmCHjuk62ddhoKXXYQV5uo5obHhV4ovwYSFggoG3eqP8CAwEAAQ==